#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 104
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 55
#define ALIAS_COUNT 0
#define TOKEN_COUNT 31
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_SEMI = 1,
  anon_sym_let = 2,
  anon_sym_EQ = 3,
  anon_sym_SLASH_SLASH = 4,
  aux_sym_comment_token1 = 5,
  anon_sym_return = 6,
  anon_sym_if = 7,
  anon_sym_LBRACE = 8,
  anon_sym_RBRACE = 9,
  anon_sym_else = 10,
  sym_identifier = 11,
  anon_sym_LBRACK = 12,
  anon_sym_COMMA = 13,
  anon_sym_RBRACK = 14,
  anon_sym_DQUOTE = 15,
  aux_sym_string_token1 = 16,
  anon_sym_fn = 17,
  anon_sym_LPAREN = 18,
  anon_sym_RPAREN = 19,
  anon_sym_true = 20,
  anon_sym_false = 21,
  anon_sym_DASH = 22,
  anon_sym_PLUS = 23,
  anon_sym_STAR = 24,
  anon_sym_SLASH = 25,
  anon_sym_GT = 26,
  anon_sym_LT = 27,
  anon_sym_EQ_EQ = 28,
  anon_sym_BANG_EQ = 29,
  sym_integer = 30,
  sym_source_file = 31,
  sym__statement = 32,
  sym_let_statement = 33,
  sym_comment = 34,
  sym_return_statement = 35,
  sym_if_expression = 36,
  sym_condition = 37,
  sym_consequence = 38,
  sym_alternative = 39,
  sym_call = 40,
  sym_array = 41,
  sym_string = 42,
  sym_function = 43,
  sym_function_body = 44,
  sym_parameter_list = 45,
  sym_argument_list = 46,
  sym__expression = 47,
  sym_boolean = 48,
  sym_unary_operator = 49,
  sym_binary_operator = 50,
  aux_sym_source_file_repeat1 = 51,
  aux_sym_consequence_repeat1 = 52,
  aux_sym_array_repeat1 = 53,
  aux_sym_parameter_list_repeat1 = 54,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SEMI] = ";",
  [anon_sym_let] = "let",
  [anon_sym_EQ] = "=",
  [anon_sym_SLASH_SLASH] = "//",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_return] = "return",
  [anon_sym_if] = "if",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_else] = "else",
  [sym_identifier] = "identifier",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_fn] = "fn",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_DASH] = "-",
  [anon_sym_PLUS] = "+",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_GT] = ">",
  [anon_sym_LT] = "<",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [sym_integer] = "integer",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_let_statement] = "let_statement",
  [sym_comment] = "comment",
  [sym_return_statement] = "return_statement",
  [sym_if_expression] = "if_expression",
  [sym_condition] = "condition",
  [sym_consequence] = "consequence",
  [sym_alternative] = "alternative",
  [sym_call] = "call",
  [sym_array] = "array",
  [sym_string] = "string",
  [sym_function] = "function",
  [sym_function_body] = "function_body",
  [sym_parameter_list] = "parameter_list",
  [sym_argument_list] = "argument_list",
  [sym__expression] = "_expression",
  [sym_boolean] = "boolean",
  [sym_unary_operator] = "unary_operator",
  [sym_binary_operator] = "binary_operator",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_consequence_repeat1] = "consequence_repeat1",
  [aux_sym_array_repeat1] = "array_repeat1",
  [aux_sym_parameter_list_repeat1] = "parameter_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_SLASH_SLASH] = anon_sym_SLASH_SLASH,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_else] = anon_sym_else,
  [sym_identifier] = sym_identifier,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [sym_integer] = sym_integer,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_let_statement] = sym_let_statement,
  [sym_comment] = sym_comment,
  [sym_return_statement] = sym_return_statement,
  [sym_if_expression] = sym_if_expression,
  [sym_condition] = sym_condition,
  [sym_consequence] = sym_consequence,
  [sym_alternative] = sym_alternative,
  [sym_call] = sym_call,
  [sym_array] = sym_array,
  [sym_string] = sym_string,
  [sym_function] = sym_function,
  [sym_function_body] = sym_function_body,
  [sym_parameter_list] = sym_parameter_list,
  [sym_argument_list] = sym_argument_list,
  [sym__expression] = sym__expression,
  [sym_boolean] = sym_boolean,
  [sym_unary_operator] = sym_unary_operator,
  [sym_binary_operator] = sym_binary_operator,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_consequence_repeat1] = aux_sym_consequence_repeat1,
  [aux_sym_array_repeat1] = aux_sym_array_repeat1,
  [aux_sym_parameter_list_repeat1] = aux_sym_parameter_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_let_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_return_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_if_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_condition] = {
    .visible = true,
    .named = true,
  },
  [sym_consequence] = {
    .visible = true,
    .named = true,
  },
  [sym_alternative] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_function] = {
    .visible = true,
    .named = true,
  },
  [sym_function_body] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_argument_list] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_operator] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_consequence_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 4,
  [10] = 10,
  [11] = 11,
  [12] = 11,
  [13] = 13,
  [14] = 14,
  [15] = 5,
  [16] = 14,
  [17] = 8,
  [18] = 13,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 6,
  [40] = 40,
  [41] = 10,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 19,
  [47] = 20,
  [48] = 43,
  [49] = 45,
  [50] = 44,
  [51] = 42,
  [52] = 31,
  [53] = 34,
  [54] = 54,
  [55] = 24,
  [56] = 54,
  [57] = 32,
  [58] = 58,
  [59] = 27,
  [60] = 21,
  [61] = 35,
  [62] = 33,
  [63] = 25,
  [64] = 28,
  [65] = 29,
  [66] = 30,
  [67] = 26,
  [68] = 23,
  [69] = 22,
  [70] = 70,
  [71] = 71,
  [72] = 71,
  [73] = 73,
  [74] = 70,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 85,
  [87] = 87,
  [88] = 88,
  [89] = 87,
  [90] = 90,
  [91] = 90,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 95,
  [100] = 100,
  [101] = 101,
  [102] = 97,
  [103] = 92,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(8);
      if (lookahead == '!') ADVANCE(4);
      if (lookahead == '"') ADVANCE(44);
      if (lookahead == '(') ADVANCE(48);
      if (lookahead == ')') ADVANCE(49);
      if (lookahead == '*') ADVANCE(54);
      if (lookahead == '+') ADVANCE(53);
      if (lookahead == ',') ADVANCE(42);
      if (lookahead == '-') ADVANCE(52);
      if (lookahead == '/') ADVANCE(56);
      if (lookahead == ';') ADVANCE(9);
      if (lookahead == '<') ADVANCE(58);
      if (lookahead == '=') ADVANCE(12);
      if (lookahead == '>') ADVANCE(57);
      if (lookahead == '[') ADVANCE(41);
      if (lookahead == ']') ADVANCE(43);
      if (lookahead == 'e') ADVANCE(28);
      if (lookahead == 'f') ADVANCE(21);
      if (lookahead == 'i') ADVANCE(27);
      if (lookahead == 'l') ADVANCE(22);
      if (lookahead == 'r') ADVANCE(26);
      if (lookahead == 't') ADVANCE(31);
      if (lookahead == '{') ADVANCE(18);
      if (lookahead == '}') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 1:
      if (lookahead == '!') ADVANCE(4);
      if (lookahead == '"') ADVANCE(44);
      if (lookahead == '(') ADVANCE(48);
      if (lookahead == ')') ADVANCE(49);
      if (lookahead == '*') ADVANCE(54);
      if (lookahead == '+') ADVANCE(53);
      if (lookahead == ',') ADVANCE(42);
      if (lookahead == '-') ADVANCE(52);
      if (lookahead == '/') ADVANCE(55);
      if (lookahead == '<') ADVANCE(58);
      if (lookahead == '=') ADVANCE(5);
      if (lookahead == '>') ADVANCE(57);
      if (lookahead == '[') ADVANCE(41);
      if (lookahead == ']') ADVANCE(43);
      if (lookahead == 'f') ADVANCE(21);
      if (lookahead == 'i') ADVANCE(27);
      if (lookahead == 't') ADVANCE(31);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 2:
      if (lookahead == '!') ADVANCE(4);
      if (lookahead == '"') ADVANCE(44);
      if (lookahead == ')') ADVANCE(49);
      if (lookahead == '*') ADVANCE(54);
      if (lookahead == '+') ADVANCE(53);
      if (lookahead == ',') ADVANCE(42);
      if (lookahead == '-') ADVANCE(52);
      if (lookahead == '/') ADVANCE(55);
      if (lookahead == '<') ADVANCE(58);
      if (lookahead == '=') ADVANCE(5);
      if (lookahead == '>') ADVANCE(57);
      if (lookahead == '[') ADVANCE(41);
      if (lookahead == ']') ADVANCE(43);
      if (lookahead == 'e') ADVANCE(28);
      if (lookahead == 'f') ADVANCE(21);
      if (lookahead == 'i') ADVANCE(27);
      if (lookahead == 't') ADVANCE(31);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 3:
      if (lookahead == ')') ADVANCE(49);
      if (lookahead == ',') ADVANCE(42);
      if (lookahead == '=') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 4:
      if (lookahead == '=') ADVANCE(60);
      END_STATE();
    case 5:
      if (lookahead == '=') ADVANCE(59);
      END_STATE();
    case 6:
      if (eof) ADVANCE(8);
      if (lookahead == '!') ADVANCE(4);
      if (lookahead == '"') ADVANCE(44);
      if (lookahead == '(') ADVANCE(48);
      if (lookahead == '*') ADVANCE(54);
      if (lookahead == '+') ADVANCE(53);
      if (lookahead == '-') ADVANCE(52);
      if (lookahead == '/') ADVANCE(56);
      if (lookahead == ';') ADVANCE(9);
      if (lookahead == '<') ADVANCE(58);
      if (lookahead == '=') ADVANCE(5);
      if (lookahead == '>') ADVANCE(57);
      if (lookahead == '[') ADVANCE(41);
      if (lookahead == 'f') ADVANCE(21);
      if (lookahead == 'i') ADVANCE(27);
      if (lookahead == 'l') ADVANCE(22);
      if (lookahead == 'r') ADVANCE(26);
      if (lookahead == 't') ADVANCE(31);
      if (lookahead == '{') ADVANCE(18);
      if (lookahead == '}') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(6)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 7:
      if (eof) ADVANCE(8);
      if (lookahead == '!') ADVANCE(4);
      if (lookahead == '"') ADVANCE(44);
      if (lookahead == '*') ADVANCE(54);
      if (lookahead == '+') ADVANCE(53);
      if (lookahead == '-') ADVANCE(52);
      if (lookahead == '/') ADVANCE(56);
      if (lookahead == ';') ADVANCE(9);
      if (lookahead == '<') ADVANCE(58);
      if (lookahead == '=') ADVANCE(5);
      if (lookahead == '>') ADVANCE(57);
      if (lookahead == '[') ADVANCE(41);
      if (lookahead == 'e') ADVANCE(28);
      if (lookahead == 'f') ADVANCE(21);
      if (lookahead == 'i') ADVANCE(27);
      if (lookahead == 'l') ADVANCE(22);
      if (lookahead == 'r') ADVANCE(26);
      if (lookahead == 't') ADVANCE(31);
      if (lookahead == '{') ADVANCE(18);
      if (lookahead == '}') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(7)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_let);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(59);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(15);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_return);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_if);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_else);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(29);
      if (lookahead == 'n') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(46);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_fn);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(13);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(61);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 6},
  [2] = {.lex_state = 6},
  [3] = {.lex_state = 6},
  [4] = {.lex_state = 6},
  [5] = {.lex_state = 6},
  [6] = {.lex_state = 6},
  [7] = {.lex_state = 6},
  [8] = {.lex_state = 6},
  [9] = {.lex_state = 6},
  [10] = {.lex_state = 7},
  [11] = {.lex_state = 6},
  [12] = {.lex_state = 6},
  [13] = {.lex_state = 6},
  [14] = {.lex_state = 6},
  [15] = {.lex_state = 6},
  [16] = {.lex_state = 6},
  [17] = {.lex_state = 6},
  [18] = {.lex_state = 6},
  [19] = {.lex_state = 7},
  [20] = {.lex_state = 7},
  [21] = {.lex_state = 6},
  [22] = {.lex_state = 6},
  [23] = {.lex_state = 6},
  [24] = {.lex_state = 6},
  [25] = {.lex_state = 6},
  [26] = {.lex_state = 6},
  [27] = {.lex_state = 6},
  [28] = {.lex_state = 6},
  [29] = {.lex_state = 6},
  [30] = {.lex_state = 6},
  [31] = {.lex_state = 6},
  [32] = {.lex_state = 6},
  [33] = {.lex_state = 6},
  [34] = {.lex_state = 6},
  [35] = {.lex_state = 6},
  [36] = {.lex_state = 6},
  [37] = {.lex_state = 6},
  [38] = {.lex_state = 6},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 2},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 2},
  [47] = {.lex_state = 2},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 1},
  [59] = {.lex_state = 1},
  [60] = {.lex_state = 1},
  [61] = {.lex_state = 1},
  [62] = {.lex_state = 1},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 1},
  [65] = {.lex_state = 1},
  [66] = {.lex_state = 1},
  [67] = {.lex_state = 1},
  [68] = {.lex_state = 1},
  [69] = {.lex_state = 1},
  [70] = {.lex_state = 1},
  [71] = {.lex_state = 1},
  [72] = {.lex_state = 1},
  [73] = {.lex_state = 1},
  [74] = {.lex_state = 1},
  [75] = {.lex_state = 1},
  [76] = {.lex_state = 6},
  [77] = {.lex_state = 6},
  [78] = {.lex_state = 6},
  [79] = {.lex_state = 1},
  [80] = {.lex_state = 6},
  [81] = {.lex_state = 3},
  [82] = {.lex_state = 3},
  [83] = {.lex_state = 3},
  [84] = {.lex_state = 3},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 3},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 3},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 45},
  [98] = {.lex_state = 3},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 14},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 45},
  [103] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SLASH_SLASH] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(96),
    [sym__statement] = STATE(2),
    [sym_let_statement] = STATE(76),
    [sym_comment] = STATE(2),
    [sym_return_statement] = STATE(76),
    [sym_if_expression] = STATE(37),
    [sym_call] = STATE(37),
    [sym_array] = STATE(37),
    [sym_string] = STATE(37),
    [sym_function] = STATE(37),
    [sym__expression] = STATE(37),
    [sym_boolean] = STATE(37),
    [sym_unary_operator] = STATE(37),
    [sym_binary_operator] = STATE(37),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_let] = ACTIONS(5),
    [anon_sym_SLASH_SLASH] = ACTIONS(7),
    [anon_sym_return] = ACTIONS(9),
    [anon_sym_if] = ACTIONS(11),
    [sym_identifier] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_fn] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(23),
    [sym_integer] = ACTIONS(25),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 15,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(7), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(9), 1,
      anon_sym_return,
    ACTIONS(11), 1,
      anon_sym_if,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_DASH,
    ACTIONS(25), 1,
      sym_integer,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(76), 2,
      sym_let_statement,
      sym_return_statement,
    STATE(3), 3,
      sym__statement,
      sym_comment,
      aux_sym_source_file_repeat1,
    STATE(37), 9,
      sym_if_expression,
      sym_call,
      sym_array,
      sym_string,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [58] = 15,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    ACTIONS(31), 1,
      anon_sym_let,
    ACTIONS(34), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(37), 1,
      anon_sym_return,
    ACTIONS(40), 1,
      anon_sym_if,
    ACTIONS(43), 1,
      sym_identifier,
    ACTIONS(46), 1,
      anon_sym_LBRACK,
    ACTIONS(49), 1,
      anon_sym_DQUOTE,
    ACTIONS(52), 1,
      anon_sym_fn,
    ACTIONS(58), 1,
      anon_sym_DASH,
    ACTIONS(61), 1,
      sym_integer,
    ACTIONS(55), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(76), 2,
      sym_let_statement,
      sym_return_statement,
    STATE(3), 3,
      sym__statement,
      sym_comment,
      aux_sym_source_file_repeat1,
    STATE(37), 9,
      sym_if_expression,
      sym_call,
      sym_array,
      sym_string,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [116] = 14,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(9), 1,
      anon_sym_return,
    ACTIONS(11), 1,
      anon_sym_if,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_DASH,
    ACTIONS(25), 1,
      sym_integer,
    ACTIONS(64), 1,
      anon_sym_RBRACE,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(7), 2,
      sym__statement,
      aux_sym_consequence_repeat1,
    STATE(76), 2,
      sym_let_statement,
      sym_return_statement,
    STATE(37), 9,
      sym_if_expression,
      sym_call,
      sym_array,
      sym_string,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [170] = 14,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(9), 1,
      anon_sym_return,
    ACTIONS(11), 1,
      anon_sym_if,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_DASH,
    ACTIONS(25), 1,
      sym_integer,
    ACTIONS(66), 1,
      anon_sym_RBRACE,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(7), 2,
      sym__statement,
      aux_sym_consequence_repeat1,
    STATE(76), 2,
      sym_let_statement,
      sym_return_statement,
    STATE(37), 9,
      sym_if_expression,
      sym_call,
      sym_array,
      sym_string,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [224] = 4,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    STATE(22), 1,
      sym_argument_list,
    ACTIONS(70), 8,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
      anon_sym_SLASH,
    ACTIONS(68), 15,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_SLASH_SLASH,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [258] = 14,
    ACTIONS(74), 1,
      anon_sym_let,
    ACTIONS(77), 1,
      anon_sym_return,
    ACTIONS(80), 1,
      anon_sym_if,
    ACTIONS(83), 1,
      anon_sym_RBRACE,
    ACTIONS(85), 1,
      sym_identifier,
    ACTIONS(88), 1,
      anon_sym_LBRACK,
    ACTIONS(91), 1,
      anon_sym_DQUOTE,
    ACTIONS(94), 1,
      anon_sym_fn,
    ACTIONS(100), 1,
      anon_sym_DASH,
    ACTIONS(103), 1,
      sym_integer,
    ACTIONS(97), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(7), 2,
      sym__statement,
      aux_sym_consequence_repeat1,
    STATE(76), 2,
      sym_let_statement,
      sym_return_statement,
    STATE(37), 9,
      sym_if_expression,
      sym_call,
      sym_array,
      sym_string,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [312] = 14,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(9), 1,
      anon_sym_return,
    ACTIONS(11), 1,
      anon_sym_if,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_DASH,
    ACTIONS(25), 1,
      sym_integer,
    ACTIONS(106), 1,
      anon_sym_RBRACE,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(15), 2,
      sym__statement,
      aux_sym_consequence_repeat1,
    STATE(76), 2,
      sym_let_statement,
      sym_return_statement,
    STATE(37), 9,
      sym_if_expression,
      sym_call,
      sym_array,
      sym_string,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [366] = 14,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(9), 1,
      anon_sym_return,
    ACTIONS(11), 1,
      anon_sym_if,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_DASH,
    ACTIONS(25), 1,
      sym_integer,
    ACTIONS(108), 1,
      anon_sym_RBRACE,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(7), 2,
      sym__statement,
      aux_sym_consequence_repeat1,
    STATE(76), 2,
      sym_let_statement,
      sym_return_statement,
    STATE(37), 9,
      sym_if_expression,
      sym_call,
      sym_array,
      sym_string,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [420] = 4,
    ACTIONS(114), 1,
      anon_sym_else,
    STATE(24), 1,
      sym_alternative,
    ACTIONS(112), 8,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
      anon_sym_SLASH,
    ACTIONS(110), 15,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_SLASH_SLASH,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [454] = 14,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(9), 1,
      anon_sym_return,
    ACTIONS(11), 1,
      anon_sym_if,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_DASH,
    ACTIONS(25), 1,
      sym_integer,
    ACTIONS(116), 1,
      anon_sym_RBRACE,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(4), 2,
      sym__statement,
      aux_sym_consequence_repeat1,
    STATE(76), 2,
      sym_let_statement,
      sym_return_statement,
    STATE(37), 9,
      sym_if_expression,
      sym_call,
      sym_array,
      sym_string,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [508] = 14,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(9), 1,
      anon_sym_return,
    ACTIONS(11), 1,
      anon_sym_if,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_DASH,
    ACTIONS(25), 1,
      sym_integer,
    ACTIONS(118), 1,
      anon_sym_RBRACE,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(9), 2,
      sym__statement,
      aux_sym_consequence_repeat1,
    STATE(76), 2,
      sym_let_statement,
      sym_return_statement,
    STATE(37), 9,
      sym_if_expression,
      sym_call,
      sym_array,
      sym_string,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [562] = 14,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(9), 1,
      anon_sym_return,
    ACTIONS(11), 1,
      anon_sym_if,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_DASH,
    ACTIONS(25), 1,
      sym_integer,
    ACTIONS(120), 1,
      anon_sym_RBRACE,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(16), 2,
      sym__statement,
      aux_sym_consequence_repeat1,
    STATE(76), 2,
      sym_let_statement,
      sym_return_statement,
    STATE(37), 9,
      sym_if_expression,
      sym_call,
      sym_array,
      sym_string,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [616] = 14,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(9), 1,
      anon_sym_return,
    ACTIONS(11), 1,
      anon_sym_if,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_DASH,
    ACTIONS(25), 1,
      sym_integer,
    ACTIONS(122), 1,
      anon_sym_RBRACE,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(7), 2,
      sym__statement,
      aux_sym_consequence_repeat1,
    STATE(76), 2,
      sym_let_statement,
      sym_return_statement,
    STATE(37), 9,
      sym_if_expression,
      sym_call,
      sym_array,
      sym_string,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [670] = 14,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(9), 1,
      anon_sym_return,
    ACTIONS(11), 1,
      anon_sym_if,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_DASH,
    ACTIONS(25), 1,
      sym_integer,
    ACTIONS(124), 1,
      anon_sym_RBRACE,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(7), 2,
      sym__statement,
      aux_sym_consequence_repeat1,
    STATE(76), 2,
      sym_let_statement,
      sym_return_statement,
    STATE(37), 9,
      sym_if_expression,
      sym_call,
      sym_array,
      sym_string,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [724] = 14,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(9), 1,
      anon_sym_return,
    ACTIONS(11), 1,
      anon_sym_if,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_DASH,
    ACTIONS(25), 1,
      sym_integer,
    ACTIONS(126), 1,
      anon_sym_RBRACE,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(7), 2,
      sym__statement,
      aux_sym_consequence_repeat1,
    STATE(76), 2,
      sym_let_statement,
      sym_return_statement,
    STATE(37), 9,
      sym_if_expression,
      sym_call,
      sym_array,
      sym_string,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [778] = 14,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(9), 1,
      anon_sym_return,
    ACTIONS(11), 1,
      anon_sym_if,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_DASH,
    ACTIONS(25), 1,
      sym_integer,
    ACTIONS(128), 1,
      anon_sym_RBRACE,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(5), 2,
      sym__statement,
      aux_sym_consequence_repeat1,
    STATE(76), 2,
      sym_let_statement,
      sym_return_statement,
    STATE(37), 9,
      sym_if_expression,
      sym_call,
      sym_array,
      sym_string,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [832] = 14,
    ACTIONS(5), 1,
      anon_sym_let,
    ACTIONS(9), 1,
      anon_sym_return,
    ACTIONS(11), 1,
      anon_sym_if,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_DASH,
    ACTIONS(25), 1,
      sym_integer,
    ACTIONS(130), 1,
      anon_sym_RBRACE,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(14), 2,
      sym__statement,
      aux_sym_consequence_repeat1,
    STATE(76), 2,
      sym_let_statement,
      sym_return_statement,
    STATE(37), 9,
      sym_if_expression,
      sym_call,
      sym_array,
      sym_string,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [886] = 2,
    ACTIONS(134), 9,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      anon_sym_else,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
      anon_sym_SLASH,
    ACTIONS(132), 15,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_SLASH_SLASH,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [915] = 2,
    ACTIONS(138), 9,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      anon_sym_else,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
      anon_sym_SLASH,
    ACTIONS(136), 15,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_SLASH_SLASH,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [944] = 2,
    ACTIONS(142), 8,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
      anon_sym_SLASH,
    ACTIONS(140), 15,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_SLASH_SLASH,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [972] = 2,
    ACTIONS(146), 8,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
      anon_sym_SLASH,
    ACTIONS(144), 15,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_SLASH_SLASH,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [1000] = 2,
    ACTIONS(150), 8,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
      anon_sym_SLASH,
    ACTIONS(148), 15,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_SLASH_SLASH,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [1028] = 2,
    ACTIONS(154), 8,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
      anon_sym_SLASH,
    ACTIONS(152), 15,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_SLASH_SLASH,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [1056] = 2,
    ACTIONS(158), 8,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
      anon_sym_SLASH,
    ACTIONS(156), 15,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_SLASH_SLASH,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [1084] = 2,
    ACTIONS(162), 8,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
      anon_sym_SLASH,
    ACTIONS(160), 15,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_SLASH_SLASH,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [1112] = 2,
    ACTIONS(166), 8,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
      anon_sym_SLASH,
    ACTIONS(164), 15,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_SLASH_SLASH,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [1140] = 4,
    ACTIONS(174), 1,
      anon_sym_SLASH,
    ACTIONS(170), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(172), 7,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(168), 8,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_SLASH_SLASH,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      sym_integer,
  [1172] = 2,
    ACTIONS(178), 8,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
      anon_sym_SLASH,
    ACTIONS(176), 15,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_SLASH_SLASH,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [1200] = 2,
    ACTIONS(182), 8,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
      anon_sym_SLASH,
    ACTIONS(180), 15,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_SLASH_SLASH,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [1228] = 2,
    ACTIONS(186), 8,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
      anon_sym_SLASH,
    ACTIONS(184), 15,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_SLASH_SLASH,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [1256] = 2,
    ACTIONS(190), 8,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
      anon_sym_SLASH,
    ACTIONS(188), 15,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_SLASH_SLASH,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [1284] = 2,
    ACTIONS(194), 8,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
      anon_sym_SLASH,
    ACTIONS(192), 15,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_SLASH_SLASH,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [1312] = 2,
    ACTIONS(198), 8,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
      anon_sym_SLASH,
    ACTIONS(196), 15,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_SLASH_SLASH,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [1340] = 2,
    ACTIONS(202), 8,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
      anon_sym_SLASH,
    ACTIONS(200), 15,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_SLASH_SLASH,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [1368] = 4,
    ACTIONS(174), 1,
      anon_sym_SLASH,
    ACTIONS(172), 7,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(204), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_SLASH_SLASH,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      sym_integer,
    ACTIONS(206), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
  [1399] = 5,
    ACTIONS(174), 1,
      anon_sym_SLASH,
    ACTIONS(210), 1,
      anon_sym_SEMI,
    ACTIONS(208), 6,
      ts_builtin_sym_end,
      anon_sym_SLASH_SLASH,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      sym_integer,
    ACTIONS(172), 7,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(212), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
  [1432] = 4,
    ACTIONS(174), 1,
      anon_sym_SLASH,
    ACTIONS(172), 7,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(214), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_SLASH_SLASH,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      sym_integer,
    ACTIONS(216), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
  [1463] = 4,
    ACTIONS(218), 1,
      anon_sym_LPAREN,
    STATE(69), 1,
      sym_argument_list,
    ACTIONS(70), 5,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(68), 14,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [1493] = 11,
    ACTIONS(220), 1,
      anon_sym_if,
    ACTIONS(223), 1,
      sym_identifier,
    ACTIONS(226), 1,
      anon_sym_LBRACK,
    ACTIONS(231), 1,
      anon_sym_DQUOTE,
    ACTIONS(234), 1,
      anon_sym_fn,
    ACTIONS(240), 1,
      anon_sym_DASH,
    ACTIONS(243), 1,
      sym_integer,
    STATE(40), 1,
      aux_sym_array_repeat1,
    ACTIONS(229), 2,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
    ACTIONS(237), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(58), 9,
      sym_if_expression,
      sym_call,
      sym_array,
      sym_string,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [1537] = 4,
    ACTIONS(246), 1,
      anon_sym_else,
    STATE(55), 1,
      sym_alternative,
    ACTIONS(112), 5,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(110), 14,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [1567] = 11,
    ACTIONS(248), 1,
      anon_sym_if,
    ACTIONS(250), 1,
      sym_identifier,
    ACTIONS(252), 1,
      anon_sym_LBRACK,
    ACTIONS(254), 1,
      anon_sym_DQUOTE,
    ACTIONS(256), 1,
      anon_sym_fn,
    ACTIONS(258), 1,
      anon_sym_RPAREN,
    ACTIONS(262), 1,
      anon_sym_DASH,
    ACTIONS(264), 1,
      sym_integer,
    STATE(40), 1,
      aux_sym_array_repeat1,
    ACTIONS(260), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(58), 9,
      sym_if_expression,
      sym_call,
      sym_array,
      sym_string,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [1610] = 11,
    ACTIONS(248), 1,
      anon_sym_if,
    ACTIONS(250), 1,
      sym_identifier,
    ACTIONS(252), 1,
      anon_sym_LBRACK,
    ACTIONS(254), 1,
      anon_sym_DQUOTE,
    ACTIONS(256), 1,
      anon_sym_fn,
    ACTIONS(262), 1,
      anon_sym_DASH,
    ACTIONS(264), 1,
      sym_integer,
    ACTIONS(266), 1,
      anon_sym_RBRACK,
    STATE(44), 1,
      aux_sym_array_repeat1,
    ACTIONS(260), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(58), 9,
      sym_if_expression,
      sym_call,
      sym_array,
      sym_string,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [1653] = 11,
    ACTIONS(248), 1,
      anon_sym_if,
    ACTIONS(250), 1,
      sym_identifier,
    ACTIONS(252), 1,
      anon_sym_LBRACK,
    ACTIONS(254), 1,
      anon_sym_DQUOTE,
    ACTIONS(256), 1,
      anon_sym_fn,
    ACTIONS(262), 1,
      anon_sym_DASH,
    ACTIONS(264), 1,
      sym_integer,
    ACTIONS(268), 1,
      anon_sym_RBRACK,
    STATE(40), 1,
      aux_sym_array_repeat1,
    ACTIONS(260), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(58), 9,
      sym_if_expression,
      sym_call,
      sym_array,
      sym_string,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [1696] = 11,
    ACTIONS(248), 1,
      anon_sym_if,
    ACTIONS(250), 1,
      sym_identifier,
    ACTIONS(252), 1,
      anon_sym_LBRACK,
    ACTIONS(254), 1,
      anon_sym_DQUOTE,
    ACTIONS(256), 1,
      anon_sym_fn,
    ACTIONS(262), 1,
      anon_sym_DASH,
    ACTIONS(264), 1,
      sym_integer,
    ACTIONS(270), 1,
      anon_sym_RPAREN,
    STATE(42), 1,
      aux_sym_array_repeat1,
    ACTIONS(260), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(58), 9,
      sym_if_expression,
      sym_call,
      sym_array,
      sym_string,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [1739] = 2,
    ACTIONS(134), 6,
      anon_sym_if,
      anon_sym_else,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(132), 14,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [1764] = 2,
    ACTIONS(138), 6,
      anon_sym_if,
      anon_sym_else,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(136), 14,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [1789] = 11,
    ACTIONS(248), 1,
      anon_sym_if,
    ACTIONS(250), 1,
      sym_identifier,
    ACTIONS(252), 1,
      anon_sym_LBRACK,
    ACTIONS(254), 1,
      anon_sym_DQUOTE,
    ACTIONS(256), 1,
      anon_sym_fn,
    ACTIONS(262), 1,
      anon_sym_DASH,
    ACTIONS(264), 1,
      sym_integer,
    ACTIONS(272), 1,
      anon_sym_RBRACK,
    STATE(50), 1,
      aux_sym_array_repeat1,
    ACTIONS(260), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(58), 9,
      sym_if_expression,
      sym_call,
      sym_array,
      sym_string,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [1832] = 11,
    ACTIONS(248), 1,
      anon_sym_if,
    ACTIONS(250), 1,
      sym_identifier,
    ACTIONS(252), 1,
      anon_sym_LBRACK,
    ACTIONS(254), 1,
      anon_sym_DQUOTE,
    ACTIONS(256), 1,
      anon_sym_fn,
    ACTIONS(262), 1,
      anon_sym_DASH,
    ACTIONS(264), 1,
      sym_integer,
    ACTIONS(274), 1,
      anon_sym_RPAREN,
    STATE(51), 1,
      aux_sym_array_repeat1,
    ACTIONS(260), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(58), 9,
      sym_if_expression,
      sym_call,
      sym_array,
      sym_string,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [1875] = 11,
    ACTIONS(248), 1,
      anon_sym_if,
    ACTIONS(250), 1,
      sym_identifier,
    ACTIONS(252), 1,
      anon_sym_LBRACK,
    ACTIONS(254), 1,
      anon_sym_DQUOTE,
    ACTIONS(256), 1,
      anon_sym_fn,
    ACTIONS(262), 1,
      anon_sym_DASH,
    ACTIONS(264), 1,
      sym_integer,
    ACTIONS(276), 1,
      anon_sym_RBRACK,
    STATE(40), 1,
      aux_sym_array_repeat1,
    ACTIONS(260), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(58), 9,
      sym_if_expression,
      sym_call,
      sym_array,
      sym_string,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [1918] = 11,
    ACTIONS(248), 1,
      anon_sym_if,
    ACTIONS(250), 1,
      sym_identifier,
    ACTIONS(252), 1,
      anon_sym_LBRACK,
    ACTIONS(254), 1,
      anon_sym_DQUOTE,
    ACTIONS(256), 1,
      anon_sym_fn,
    ACTIONS(262), 1,
      anon_sym_DASH,
    ACTIONS(264), 1,
      sym_integer,
    ACTIONS(278), 1,
      anon_sym_RPAREN,
    STATE(40), 1,
      aux_sym_array_repeat1,
    ACTIONS(260), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(58), 9,
      sym_if_expression,
      sym_call,
      sym_array,
      sym_string,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [1961] = 2,
    ACTIONS(186), 5,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(184), 14,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [1985] = 2,
    ACTIONS(198), 5,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(196), 14,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [2009] = 10,
    ACTIONS(11), 1,
      anon_sym_if,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_DASH,
    ACTIONS(280), 1,
      sym_integer,
    STATE(87), 1,
      sym_condition,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(80), 9,
      sym_if_expression,
      sym_call,
      sym_array,
      sym_string,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [2049] = 2,
    ACTIONS(154), 5,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(152), 14,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [2073] = 10,
    ACTIONS(11), 1,
      anon_sym_if,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_DASH,
    ACTIONS(280), 1,
      sym_integer,
    STATE(89), 1,
      sym_condition,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(80), 9,
      sym_if_expression,
      sym_call,
      sym_array,
      sym_string,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [2113] = 2,
    ACTIONS(190), 5,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(188), 14,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [2137] = 4,
    ACTIONS(286), 1,
      anon_sym_COMMA,
    ACTIONS(282), 5,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(284), 5,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_RPAREN,
      sym_integer,
    ACTIONS(288), 8,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [2165] = 2,
    ACTIONS(166), 5,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(164), 14,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [2189] = 2,
    ACTIONS(142), 5,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(140), 14,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [2213] = 2,
    ACTIONS(202), 5,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(200), 14,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [2237] = 2,
    ACTIONS(194), 5,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(192), 14,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [2261] = 2,
    ACTIONS(158), 5,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(156), 14,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [2285] = 3,
    ACTIONS(170), 5,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(168), 6,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_RPAREN,
      sym_integer,
    ACTIONS(288), 8,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [2311] = 2,
    ACTIONS(178), 5,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(176), 14,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [2335] = 2,
    ACTIONS(182), 5,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(180), 14,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [2359] = 2,
    ACTIONS(162), 5,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(160), 14,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [2383] = 2,
    ACTIONS(150), 5,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(148), 14,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [2407] = 2,
    ACTIONS(146), 5,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(144), 14,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      sym_integer,
  [2431] = 9,
    ACTIONS(248), 1,
      anon_sym_if,
    ACTIONS(250), 1,
      sym_identifier,
    ACTIONS(252), 1,
      anon_sym_LBRACK,
    ACTIONS(254), 1,
      anon_sym_DQUOTE,
    ACTIONS(256), 1,
      anon_sym_fn,
    ACTIONS(262), 1,
      anon_sym_DASH,
    ACTIONS(290), 1,
      sym_integer,
    ACTIONS(260), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(64), 9,
      sym_if_expression,
      sym_call,
      sym_array,
      sym_string,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [2468] = 9,
    ACTIONS(248), 1,
      anon_sym_if,
    ACTIONS(250), 1,
      sym_identifier,
    ACTIONS(252), 1,
      anon_sym_LBRACK,
    ACTIONS(254), 1,
      anon_sym_DQUOTE,
    ACTIONS(256), 1,
      anon_sym_fn,
    ACTIONS(262), 1,
      anon_sym_DASH,
    ACTIONS(292), 1,
      sym_integer,
    ACTIONS(260), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(57), 9,
      sym_if_expression,
      sym_call,
      sym_array,
      sym_string,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [2505] = 9,
    ACTIONS(11), 1,
      anon_sym_if,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_DASH,
    ACTIONS(294), 1,
      sym_integer,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(32), 9,
      sym_if_expression,
      sym_call,
      sym_array,
      sym_string,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [2542] = 9,
    ACTIONS(11), 1,
      anon_sym_if,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_DASH,
    ACTIONS(296), 1,
      sym_integer,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 9,
      sym_if_expression,
      sym_call,
      sym_array,
      sym_string,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [2579] = 9,
    ACTIONS(11), 1,
      anon_sym_if,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_DASH,
    ACTIONS(298), 1,
      sym_integer,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(28), 9,
      sym_if_expression,
      sym_call,
      sym_array,
      sym_string,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [2616] = 9,
    ACTIONS(11), 1,
      anon_sym_if,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_fn,
    ACTIONS(23), 1,
      anon_sym_DASH,
    ACTIONS(300), 1,
      sym_integer,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(36), 9,
      sym_if_expression,
      sym_call,
      sym_array,
      sym_string,
      sym_function,
      sym__expression,
      sym_boolean,
      sym_unary_operator,
      sym_binary_operator,
  [2653] = 3,
    ACTIONS(210), 1,
      anon_sym_SEMI,
    ACTIONS(208), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH_SLASH,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      sym_integer,
    ACTIONS(212), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
  [2675] = 2,
    ACTIONS(302), 7,
      ts_builtin_sym_end,
      anon_sym_SLASH_SLASH,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      sym_integer,
    ACTIONS(304), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
  [2694] = 2,
    ACTIONS(306), 6,
      ts_builtin_sym_end,
      anon_sym_SLASH_SLASH,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_DASH,
      sym_integer,
    ACTIONS(308), 7,
      anon_sym_let,
      anon_sym_return,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
  [2712] = 2,
    ACTIONS(310), 5,
      anon_sym_if,
      sym_identifier,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(229), 6,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_RPAREN,
      anon_sym_DASH,
      sym_integer,
  [2728] = 2,
    ACTIONS(312), 1,
      anon_sym_LBRACE,
    ACTIONS(172), 8,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_GT,
      anon_sym_LT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [2742] = 3,
    ACTIONS(314), 1,
      sym_identifier,
    ACTIONS(316), 1,
      anon_sym_RPAREN,
    STATE(84), 1,
      aux_sym_parameter_list_repeat1,
  [2752] = 2,
    ACTIONS(320), 1,
      anon_sym_COMMA,
    ACTIONS(318), 2,
      sym_identifier,
      anon_sym_RPAREN,
  [2760] = 3,
    ACTIONS(322), 1,
      sym_identifier,
    ACTIONS(325), 1,
      anon_sym_RPAREN,
    STATE(83), 1,
      aux_sym_parameter_list_repeat1,
  [2770] = 3,
    ACTIONS(314), 1,
      sym_identifier,
    ACTIONS(327), 1,
      anon_sym_RPAREN,
    STATE(83), 1,
      aux_sym_parameter_list_repeat1,
  [2780] = 2,
    ACTIONS(329), 1,
      anon_sym_LBRACE,
    STATE(52), 1,
      sym_function_body,
  [2787] = 2,
    ACTIONS(331), 1,
      anon_sym_LBRACE,
    STATE(31), 1,
      sym_function_body,
  [2794] = 2,
    ACTIONS(333), 1,
      anon_sym_LBRACE,
    STATE(41), 1,
      sym_consequence,
  [2801] = 1,
    ACTIONS(325), 2,
      sym_identifier,
      anon_sym_RPAREN,
  [2806] = 2,
    ACTIONS(335), 1,
      anon_sym_LBRACE,
    STATE(10), 1,
      sym_consequence,
  [2813] = 2,
    ACTIONS(337), 1,
      anon_sym_LPAREN,
    STATE(86), 1,
      sym_parameter_list,
  [2820] = 2,
    ACTIONS(337), 1,
      anon_sym_LPAREN,
    STATE(85), 1,
      sym_parameter_list,
  [2827] = 1,
    ACTIONS(339), 1,
      anon_sym_LBRACE,
  [2831] = 1,
    ACTIONS(341), 1,
      anon_sym_EQ,
  [2835] = 1,
    ACTIONS(343), 1,
      anon_sym_LBRACE,
  [2839] = 1,
    ACTIONS(345), 1,
      anon_sym_DQUOTE,
  [2843] = 1,
    ACTIONS(347), 1,
      ts_builtin_sym_end,
  [2847] = 1,
    ACTIONS(349), 1,
      aux_sym_string_token1,
  [2851] = 1,
    ACTIONS(351), 1,
      sym_identifier,
  [2855] = 1,
    ACTIONS(353), 1,
      anon_sym_DQUOTE,
  [2859] = 1,
    ACTIONS(355), 1,
      aux_sym_comment_token1,
  [2863] = 1,
    ACTIONS(357), 1,
      anon_sym_LBRACE,
  [2867] = 1,
    ACTIONS(359), 1,
      aux_sym_string_token1,
  [2871] = 1,
    ACTIONS(361), 1,
      anon_sym_LBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 58,
  [SMALL_STATE(4)] = 116,
  [SMALL_STATE(5)] = 170,
  [SMALL_STATE(6)] = 224,
  [SMALL_STATE(7)] = 258,
  [SMALL_STATE(8)] = 312,
  [SMALL_STATE(9)] = 366,
  [SMALL_STATE(10)] = 420,
  [SMALL_STATE(11)] = 454,
  [SMALL_STATE(12)] = 508,
  [SMALL_STATE(13)] = 562,
  [SMALL_STATE(14)] = 616,
  [SMALL_STATE(15)] = 670,
  [SMALL_STATE(16)] = 724,
  [SMALL_STATE(17)] = 778,
  [SMALL_STATE(18)] = 832,
  [SMALL_STATE(19)] = 886,
  [SMALL_STATE(20)] = 915,
  [SMALL_STATE(21)] = 944,
  [SMALL_STATE(22)] = 972,
  [SMALL_STATE(23)] = 1000,
  [SMALL_STATE(24)] = 1028,
  [SMALL_STATE(25)] = 1056,
  [SMALL_STATE(26)] = 1084,
  [SMALL_STATE(27)] = 1112,
  [SMALL_STATE(28)] = 1140,
  [SMALL_STATE(29)] = 1172,
  [SMALL_STATE(30)] = 1200,
  [SMALL_STATE(31)] = 1228,
  [SMALL_STATE(32)] = 1256,
  [SMALL_STATE(33)] = 1284,
  [SMALL_STATE(34)] = 1312,
  [SMALL_STATE(35)] = 1340,
  [SMALL_STATE(36)] = 1368,
  [SMALL_STATE(37)] = 1399,
  [SMALL_STATE(38)] = 1432,
  [SMALL_STATE(39)] = 1463,
  [SMALL_STATE(40)] = 1493,
  [SMALL_STATE(41)] = 1537,
  [SMALL_STATE(42)] = 1567,
  [SMALL_STATE(43)] = 1610,
  [SMALL_STATE(44)] = 1653,
  [SMALL_STATE(45)] = 1696,
  [SMALL_STATE(46)] = 1739,
  [SMALL_STATE(47)] = 1764,
  [SMALL_STATE(48)] = 1789,
  [SMALL_STATE(49)] = 1832,
  [SMALL_STATE(50)] = 1875,
  [SMALL_STATE(51)] = 1918,
  [SMALL_STATE(52)] = 1961,
  [SMALL_STATE(53)] = 1985,
  [SMALL_STATE(54)] = 2009,
  [SMALL_STATE(55)] = 2049,
  [SMALL_STATE(56)] = 2073,
  [SMALL_STATE(57)] = 2113,
  [SMALL_STATE(58)] = 2137,
  [SMALL_STATE(59)] = 2165,
  [SMALL_STATE(60)] = 2189,
  [SMALL_STATE(61)] = 2213,
  [SMALL_STATE(62)] = 2237,
  [SMALL_STATE(63)] = 2261,
  [SMALL_STATE(64)] = 2285,
  [SMALL_STATE(65)] = 2311,
  [SMALL_STATE(66)] = 2335,
  [SMALL_STATE(67)] = 2359,
  [SMALL_STATE(68)] = 2383,
  [SMALL_STATE(69)] = 2407,
  [SMALL_STATE(70)] = 2431,
  [SMALL_STATE(71)] = 2468,
  [SMALL_STATE(72)] = 2505,
  [SMALL_STATE(73)] = 2542,
  [SMALL_STATE(74)] = 2579,
  [SMALL_STATE(75)] = 2616,
  [SMALL_STATE(76)] = 2653,
  [SMALL_STATE(77)] = 2675,
  [SMALL_STATE(78)] = 2694,
  [SMALL_STATE(79)] = 2712,
  [SMALL_STATE(80)] = 2728,
  [SMALL_STATE(81)] = 2742,
  [SMALL_STATE(82)] = 2752,
  [SMALL_STATE(83)] = 2760,
  [SMALL_STATE(84)] = 2770,
  [SMALL_STATE(85)] = 2780,
  [SMALL_STATE(86)] = 2787,
  [SMALL_STATE(87)] = 2794,
  [SMALL_STATE(88)] = 2801,
  [SMALL_STATE(89)] = 2806,
  [SMALL_STATE(90)] = 2813,
  [SMALL_STATE(91)] = 2820,
  [SMALL_STATE(92)] = 2827,
  [SMALL_STATE(93)] = 2831,
  [SMALL_STATE(94)] = 2835,
  [SMALL_STATE(95)] = 2839,
  [SMALL_STATE(96)] = 2843,
  [SMALL_STATE(97)] = 2847,
  [SMALL_STATE(98)] = 2851,
  [SMALL_STATE(99)] = 2855,
  [SMALL_STATE(100)] = 2859,
  [SMALL_STATE(101)] = 2863,
  [SMALL_STATE(102)] = 2867,
  [SMALL_STATE(103)] = 2871,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(98),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(90),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(98),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(100),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(75),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(56),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(6),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(43),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(97),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(90),
  [55] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(34),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(74),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(37),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [74] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_consequence_repeat1, 2), SHIFT_REPEAT(98),
  [77] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_consequence_repeat1, 2), SHIFT_REPEAT(75),
  [80] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_consequence_repeat1, 2), SHIFT_REPEAT(56),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_consequence_repeat1, 2),
  [85] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_consequence_repeat1, 2), SHIFT_REPEAT(6),
  [88] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_consequence_repeat1, 2), SHIFT_REPEAT(43),
  [91] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_consequence_repeat1, 2), SHIFT_REPEAT(97),
  [94] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_consequence_repeat1, 2), SHIFT_REPEAT(90),
  [97] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_consequence_repeat1, 2), SHIFT_REPEAT(34),
  [100] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_consequence_repeat1, 2), SHIFT_REPEAT(74),
  [103] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_consequence_repeat1, 2), SHIFT_REPEAT(37),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_expression, 3),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_expression, 3),
  [114] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_consequence, 2),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_consequence, 2),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_consequence, 3),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_consequence, 3),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alternative, 4),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_alternative, 4),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 2),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 2),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 2),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_expression, 4),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_expression, 4),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_body, 2),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_body, 2),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 3),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 3),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_operator, 2),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_operator, 2),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [174] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alternative, 3),
  [178] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_alternative, 3),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_body, 3),
  [182] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_body, 3),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 3),
  [186] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function, 3),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_operator, 3),
  [190] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_operator, 3),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 2),
  [194] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 2),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1),
  [198] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3),
  [202] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 3),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_statement, 2),
  [206] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_statement, 2),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 1),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [212] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement, 1),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_statement, 4),
  [216] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let_statement, 4),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [220] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(54),
  [223] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(39),
  [226] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(48),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2),
  [231] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(102),
  [234] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(91),
  [237] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(53),
  [240] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(70),
  [243] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(58),
  [246] = {.entry = {.count = 1, .reusable = false}}, SHIFT(103),
  [248] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [250] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [256] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [260] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [282] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 1),
  [284] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 1),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [302] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 2),
  [304] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement, 2),
  [306] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2),
  [308] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 2),
  [310] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 2),
  [312] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition, 1),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [318] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 1),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [322] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2), SHIFT_REPEAT(82),
  [325] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [343] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 2),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [347] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [353] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [357] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 3),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [361] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_monkey(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
